### ISSUE TITLE
Port opening error

### ISSUE THREAD

**Issue by rohinrohin** [the-AjK/GT-511C3#17]
I am trying to connect the pi to the GT-511C3. However, I get the following error with your sample code. 

```
init GT511-C3 at 9600 baud...
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: Port is opening
    at SerialPort.open (/home/rohin/fingerprint/node_modules/gt511c3/node_modules/serialport/lib/serialport.js:160:24)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
```

Note: When I try to open the same port /dev/ttyS1 in python (pyserial) or even through screen. The port opens fine. 

I was unable to install serialportv2 (as per your package spec), I had installed serialport v4.0.7 instead. 

Would that be causing this?

May be helpful - 
```
node -v
v7.6.0
```

Any help is appreciated. Thanks!

**Comment by rohinrohin** [comment]
**Update**: no port error when I run the following

```
var SerialPort = require('serialport');
var port = new SerialPort('/dev/ttyS1');

port.on('open', function() {
  port.write('main screen turn on', function(err) {
    if (err) {
      return console.log('Error on write: ', err.message);
    }
    console.log('message written'); // this log message runs => port opened w/o error

  });
});

// open errors will be emitted as an error event
port.on('error', function(err) {
  console.log('Error: ', err.message);
})

```
